### ISSUE TITLE
Request returns 429 error!

### ISSUE THREAD

**Issue by Mark-a-ops** [jpetzke/AutoGPT-Instagram#2]
I got this error during starting AutoGPT with this plug:
    _**Request returns 429 error! That means 'too many requests'. I'll go to sleep for 5 minutes.**_

How to fix it? Thanks!

**Comment by jpetzke** [comment]
It means that AutoGPT sent too many requests to Instagram. Usually it's fixed by waiting for a bit (instagram time outed you, probably)

**Comment by Mark-a-ops** [comment]
I waited many times, and used three VMs from different regions, but still got this error, :(

**Comment by jpetzke** [comment]
Hmm that's unusual. Can you try to use a different Instagram account?

**Comment by AlexeyDep** [comment]
Hi. A similar problem. Goes into standby mode and error 429

![problems_insta](https://user-images.githubusercontent.com/95611462/235872094-42bfd097-d7ea-4363-8f3d-4fe71d5f3fc2.jpg)

**Comment by AlexeyDep** [comment]
maybe I did something wrong with the settings.

**Comment by jpetzke** [comment]
Again, try to use a different Account
